### ISSUE TITLE
AttributeError: 'KeyError' object has no attribute 'iter_versions'

### ISSUE THREAD

**Issue by JonathonReinhart** [JonathonReinhart/staticx#177]
Reported in #176 by @MrJacobBaker. I just wanted to spell out the exact issue for posterity.

Attempting to run staticx against a non-GLIBC executable produces the following error:
```
Traceback (most recent call last):
  File "venv/bin/staticx", line 8, in <module>
    sys.exit(main())
  File "staticx/__main__.py", line 55, in main
    debug = args.debug,
  File "staticx/api.py", line 137, in generate
    strip=strip, compress=compress, debug=debug) as ar:
  File "staticx/api.py", line 46, in generate_archive
    debug = debug,
  File "staticx/hooks/__init__.py", line 18, in run_hooks
    hook(ctx)
  File "hooks/glibc.py", line 10, in process_glibc_prog
    if not is_linked_against_glibc(ctx.orig_prog):
  File "staticx/hooks/glibc.py", line 40, in is_linked_against_glibc
    for verneed, vernaux_iter in sec.iter_versions():
AttributeError: 'KeyError' object has no attribute 'iter_versions'
```

**Comment by JonathonReinhart** [comment]
This bug was introduced in #139 around 7de0617a. There are (at least) three problems here:
1. `get_section()` will [*`return`*, rather than *`raise`* a `KeyError`](https://github.com/JonathonReinhart/staticx/blob/1446286bfe36e5defb081c04836b8842bec705cd/staticx/elf.py#L254). :facepalm: 
2. `is_linked_against_glibc()` does nothing to handle the case where [`get_section(elf, GNUVerNeedSection)`](https://github.com/JonathonReinhart/staticx/blob/1446286bfe36e5defb081c04836b8842bec705cd/staticx/hooks/glibc.py#L39) might fail.
3. There are clearly no tests which exercise this code path.
